import type { CourseInfo, Qsolver, Reading, transcribe } from '../types';

export const courseInfo: CourseInfo = {
  "courseBasicInfo": {
    "courseTitle": "Foundations of Finance",
    "school": "NYU Stern",
    "courseCode": "FINC-UB.0002.001, FINC-UB.0002.002",
    "credits": "not mentioned in the syllabus",
    "semester": "Spring 2025",
    "department": "Finance"
  },
  "instructorInfo": {
    "instructorName": "Toomas Laarits",
    "titlePosition": "Professor",
    "officeAddress": "KMC 9\u201355",
    "officeHours": "Mondays 11am-12pm; Wednesdays 4-5pm",
    "contactInfo": {
      "email": "tlaarits@stern.nyu.edu",
      "phone": "not mentioned in the syllabus"
    }
  },
  "assessmentAndGradingPolicy": {
    "weightings": {
      "assignments": "20%",
      "quizzes": "not mentioned in the syllabus",
      "midterm": "30%",
      "final": "40%",
      "projects": "not mentioned in the syllabus",
      "attendance": "10%"
    },
    "assessmentMethods": [
      "Homework",
      "Midterm exam",
      "Final exam",
      "Participation"
    ]
  }
};

export const productUsingInCourse: Qsolver = {
  "title": "How Asksia AI Qsolver Can Enhance Your Course Study",
  "description": "Asksia AI Qsolver can help you master the core concepts of asset valuation in NYU Stern's Foundations of Finance course, from time value of money to derivatives, by providing in-depth explanations and solving practice problems.",
  "coreFeatures": [
    {
      "name": "Explain Deeper",
      "description": "Asksia AI Qsolver can help you understand complex concepts like the Capital Asset Pricing Model (CAPM) and arbitrage pricing theory in greater depth, as covered in the course syllabus."
    },
    {
      "name": "Explain Easier",
      "description": "Asksia AI Qsolver simplifies challenging topics such as portfolio selection and efficient portfolios, making them easier to grasp for improved understanding of the course material."
    },
    {
      "name": "Check Answer",
      "description": "Asksia AI Qsolver allows you to verify your answers for homework assignments, particularly those involving Excel applications, ensuring you understand the concepts related to time value of money, bond pricing, and option valuation."
    },
    {
      "name": "Visualization",
      "description": "Asksia AI Qsolver can generate visualizations of financial concepts such as the yield curve and efficient frontiers, aiding comprehension of the course's quantitative aspects."
    }
  ]
};

export const productUsingInCoursereading: Reading = {
  "title": "How Asksia Reading Can Enhance Your Course Study",
  "description": "Asksia Reading can significantly improve your learning experience in Foundations of Finance by efficiently processing course materials like lecture slides, handouts, and the recommended textbook, \"Essentials of Investments.\"",
  "coreFeatures": [
    {
      "name": "Multi-Document Support",
      "description": "Asksia Reading allows for the simultaneous analysis of multiple documents, such as lecture slides and textbook chapters, facilitating a comprehensive understanding of concepts like the CAPM and portfolio selection."
    },
    {
      "name": "Language Selection",
      "description": "While not explicitly mentioned in the syllabus, Asksia Reading's multilingual support could benefit students needing to access supplemental financial materials in different languages."
    },
    {
      "name": "Automated Summaries",
      "description": "Asksia Reading can generate summaries of lengthy readings on topics like bond pricing, option valuation, and arbitrage, saving students time while ensuring they grasp the core concepts."
    },
    {
      "name": "Outline Recognition",
      "description": "Asksia Reading can help students navigate the course structure by creating outlines from provided materials, making it easier to follow the progression of topics from the time value of money to derivatives."
    }
  ]
};

export const productUsingInCoursetranscribe: transcribe = {
  "title": "What can you do using Asksia AI Transcribe for your course study?",
  "description": "Asksia AI Transcribe helps international students in NYU Stern's Foundations of Finance course overcome language barriers and improve comprehension of course material.",
  "coreFeatures": "- Multilingual transcription of class recordings (lectures are recorded, as stated in the syllabus) allows for review in your native language, directly addressing potential language barriers for international students.\n- Detailed class outlines generated by Asksia AI Transcribe can be used to supplement the lecture slides and handouts provided on the course website, aiding in review and study for exams.\n- The AI Classroom Assistant feature can provide additional support for understanding complex topics like present value, risk, diversification, arbitrage, and option value, key concepts in the course.\n- Real-time translation during lectures would allow immediate clarification of any unclear concepts, fostering a smoother learning experience and maximizing participation in class discussions, contributing to the 10% participation grade.\n- Transcription of the lectures ensures that students can review missed material or revisit confusing concepts even if they are absent from class due to religious observances or other legitimate reasons, as per NYU's policy.\n- Asksia AI Transcribe can be used to create easily searchable transcripts which can be utilized along with the suggested textbook and other course materials, including the concept questions posted after each lecture."
};
