import json
with open('tutor/dataformat.json', 'r') as f:
        data = json.load(f)

course_info = data["courseInfo"]
product_using = data["productUsingInCourse"]
product_reading = data["productUsingInCoursereading"]
product_transcribe = data["productUsingInCoursetranscribe"]
faq = data["FAQ"]

        # Args:
        #     history: 对话历史记录列表，每个记录包含 role 和 parts
        #         格式: [{"role": "user"/"model", "parts": ["消息内容"]}]
        #     system_instruction: 可选，系统指令，用于设置模型的行为
solver = """
sover-Focuses on problem-solving, helping students resolve question-and-answer type issues.
features:
1.EXPLAIN DEEPER
specializing in delivering in-depth academic knowledge through streaming responses. The core mission is to provide layered, progressively deeper explanations that enhance understanding while maintaining engagement
2.EXPLAIN EASIER
specializing in making complex concepts simple and accessible. Your primary goal is to break down complicated academic topics into easy-to-understand explanations while maintaining accuracy. 
3.CHECK ANSWER
Sia will conduct a deep dive into the answers from aspects such as whether the calculations are correct,whether logic is correct,and the completeness of the answers.
4.VISUALIZATION
Visualization will generate images to assist in understanding the relevant content in the text,especially suitable for topics in engineering that require visual aids for comprehension.
"""
reading = """
Reading-Focuses on reading materials, assisting students with reading difficulties
features:
1.Support for Multiple Document Uploads
Users can upload multiple documents and switch between them at any time. Currently, PDF materials are supported for upload, with a maximum of 5 documents allowed. Each document can be up to 20MB in size and a maximum of 500 pages can be read.
2.Automatic Reference Locking to Original Text
A smart reference positioning function has been introduced. When citing reading materials, it can automatically jump to or lock onto the corresponding position in the original text. This reduces the time and operational costs of finding citation sources and enhances the accuracy and efficiency of literature referencing.
3.Automatic Summary of Reading Materials
By clicking the "Summary" button on the right-hand toolbar, users can view the content summary automatically generated by Super for the PDF. This helps users quickly understand the main points discussed in the article.
4.Article Structure Recognition
Similarly, by clicking the "Outline" button on the right-hand toolbar, users can view the article structure automatically generated by Super. This allows for a quick understanding of the article's structure. The structure also supports text locking for desired positions.
"""
transcribe = """
Transcribe Classroom Recordings
features:
1.Upload local audio files, and Asksia will transcribe the audio into multilingual subtitles, providing services such as intelligent summary, ChatBox Q&A, Assistant analysis, and Chinese translation to help students review classroom content more effectively.
2.Local File Upload
Supports uploading mainstream audio and video formats such as MP4, WAV, etc. It also enables multilingual transcription and translation. Once processed, the files will be stored in the "My Records" section.
3.Smart Outline
After the transcription is complete, the outline will automatically display detailed information, including keywords, main content, and key sentences from the classroom recording.
4.Dual-Screen Interaction
On the left side of the transcription page, the original content and translated content are displayed side by side. The recorded audio can be played simultaneously, with subtitles following the progress bar. On the right side, the Assistant AI will automatically generate relevant questions and answers based on the classroom content.
"""
system_instruction_header = """
your job is generate content for the website asksia.ai
generating structured content based on the product's features and your positioning. 
This content will be used for introducing the product to browsing users.
"""
