import type { CourseInfo, Qsolver, Reading, transcribe } from '../../types';

export const courseInfo: CourseInfo = {
  "courseBasicInfo": {
    "courseTitle": "Foundations of Finance",
    "school": "NYU",
    "courseCode": "FINC-UB.0002.001, FINC-UB.0002.002",
    "credits": "not mentioned in the syllabus",
    "semester": "Spring 2025",
    "department": "Stern"
  },
  "instructorInfo": {
    "instructorName": "Toomas Laarits",
    "titlePosition": "Professor",
    "officeAddress": "KMC 9\u201355",
    "officeHours": "Mondays 11am-12pm; Wednesdays 4-5pm",
    "contactInfo": {
      "email": "tlaarits@stern.nyu.edu",
      "phone": "not mentioned in the syllabus"
    }
  },
  "assessmentAndGradingPolicy": {
    "weightings": {
      "assignments": "20%",
      "quizzes": "not mentioned in the syllabus",
      "midterm": "30%",
      "final": "40%",
      "projects": "not mentioned in the syllabus",
      "attendance": "10%"
    },
    "assessmentMethods": [
      "Participation",
      "Homework",
      "Midterm",
      "Final"
    ]
  }
};

export const productUsingInCourse: Qsolver = {
  "title": "How Asksia AI Qsolver Can Enhance Your Course Study",
  "description": "Asksia AI Qsolver can help you master the core concepts of asset valuation, portfolio selection, and derivatives in NYU Stern's Foundations of Finance course by providing in-depth explanations and solving practice problems.",
  "coreFeatures": [
    {
      "name": "Explain Deeper",
      "description": "Asksia AI Qsolver can provide deeper explanations of complex topics like the Capital Asset Pricing Model (CAPM) and arbitrage pricing, enhancing your understanding of the course material."
    },
    {
      "name": "Explain Easier",
      "description": "Asksia AI Qsolver simplifies challenging concepts such as present value calculations and bond valuation, making them easier to grasp and improving your problem-solving skills for homework assignments."
    },
    {
      "name": "Check Answer",
      "description": "Asksia AI Qsolver helps you verify your answers to practice problems and homework assignments related to portfolio selection and fixed income securities, identifying any mistakes and guiding you toward the correct solutions."
    },
    {
      "name": "Visualization",
      "description": "Asksia AI Qsolver can generate visualizations like graphs and diagrams to illustrate concepts such as efficient portfolios and the yield curve, enhancing your visual learning and comprehension of the course material."
    }
  ]
};

export const productUsingInCoursereading: Reading = {
  "title": "How Asksia Reading Can Enhance Your Course Study",
  "description": "Asksia Reading can significantly improve your learning experience in the NYU Stern Foundations of Finance course by efficiently processing the course materials and facilitating deeper understanding of key concepts like present value, risk, and arbitrage.",
  "coreFeatures": [
    {
      "name": "Multi-Document Support",
      "description": "Asksia Reading's support for multiple documents will help students synthesize information from the lecture slides, handouts, and the recommended textbook, \"Essentials of Investments,\"  to master the course material."
    },
    {
      "name": "Language Selection",
      "description": "While not explicitly mentioned in the syllabus, Asksia Reading's language support could benefit international students or those needing materials in alternative languages to enhance their understanding of complex financial concepts."
    },
    {
      "name": "Automated Summaries",
      "description": "Asksia Reading can generate summaries of lengthy readings such as chapters from \"Essentials of Investments\" or detailed lecture slides, allowing students to quickly grasp key concepts related to topics like portfolio selection, CAPM, or fixed income securities."
    },
    {
      "name": "Outline Recognition",
      "description": "Asksia Reading's outline recognition feature will help students navigate the structure of complex documents such as the textbook and lecture notes, allowing them to easily locate relevant sections on topics covered in each class, as detailed in the course outline."
    }
  ]
};

export const productUsingInCoursetranscribe: transcribe = {
  "title": "What can you do using Asksia AI Transcribe for your course study?",
  "description": "Asksia AI Transcribe helps international students in NYU Stern's Foundations of Finance course overcome language barriers and improve comprehension of course material.",
  "coreFeatures": "- Multilingual transcription of class recordings allows students to review lectures in their native language, which is especially beneficial given the quantitative nature of the course and the importance of understanding concepts such as present value, risk, diversification, arbitrage, and option value. \n- Detailed class outlines generated by Asksia AI Transcribe can help students follow along during lectures, review complex topics like portfolio selection, equilibrium asset pricing (CAPM), equity valuation, arbitrage pricing, fixed income securities, and derivatives, and prepare for exams. \n- The AI classroom assistant feature can provide additional support for understanding challenging concepts, which will be helpful for students who may be less familiar with financial instruments and markets. \n- Asksia AI Transcribe's seamless learning enhancement promotes better comprehension, helping students keep pace with the rigorous curriculum and succeed in assignments, including the four homework assignments that require Excel skills. \n- The tool facilitates easier review of lecture content, which is crucial given the course's two exams (midterm and final) covering topics such as the time value of money, portfolio selection, equilibrium asset pricing, equity valuation, arbitrage pricing, fixed income securities and derivatives. \n- Given that class recordings will be available, Asksia AI Transcribe can be used to generate transcripts of recorded lectures, enabling students to review the lectures at their convenience. \n- The transcriptions will assist in understanding and reviewing material from each class, complementing the course materials, lecture slides, handouts, and practice exam questions provided on the course website.  \n- The tool's availability aligns well with the professor's plan to record all class meetings, providing a convenient alternative for students who may miss a class or need additional time to process the lecture content."
};
